/* Generated by tools/import_maps.py; do not edit. */
#ifndef SOKOBAN_MAPS_H
#define SOKOBAN_MAPS_H

#include <stdint.h>

#define SOK_LEVEL_COUNT 60
#define SOK_MAX_CRATES 36
#define SOK_MAX_CELLS 580
#define SOK_MAX_MAP_WIDTH 29
#define SOK_MAX_MAP_HEIGHT 20

enum SokTerrain {
    SOK_VOID = 0,
    SOK_WALL = 1,
    SOK_FLOOR = 2,
    SOK_GOAL = 3
};

/* Row-major cells; terrain uses four 2-bit cells per byte, low bits first. */
typedef struct SokMap {
    uint8_t width;
    uint8_t height;
    uint8_t crate_count;
    uint16_t player;
    const uint8_t *terrain;
    const uint16_t *crates;
} SokMap;

extern const SokMap sok_maps[SOK_LEVEL_COUNT];
/* SHA-256 of the exact pinned upstream plain-text map source. */
extern const uint8_t sok_map_pack_hash[32];
uint8_t sok_map_terrain(const SokMap *map, uint16_t cell);
/* IDs are 1..60. Returns NULL for an invalid ID. */
const SokMap *sok_get_map(unsigned level_id);

#endif
