#!/usr/bin/env python3
"""Audit all 60 map dimensions against old/new square-tile viewports.

Read actual renderer constants and optionally compare the native renderer CSV.
This reports geometry; it cannot establish physical LCD readability.
"""
from __future__ import annotations

import argparse
from collections import Counter
import csv
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
BEFORE = {"x": 124, "y": 28, "width": 268, "height": 172}


def current_viewport():
    source = (ROOT / "include/render.h").read_text()
    constants = {key: int(value) for key, value in
                 re.findall(r"(SOK_[A-Z_]+)\s*=\s*(\d+)", source)}
    return {"x": constants["SOK_BOARD_LEFT"], "y": constants["SOK_PLAY_TOP"],
            "width": constants["SOK_BOARD_WIDTH"], "height": constants["SOK_PLAY_HEIGHT"]}


def layout(width, height, viewport):
    wcap, hcap = viewport["width"] // width, viewport["height"] // height
    tile = min(wcap, hcap)
    return {"x": viewport["x"] + (viewport["width"] - width * tile) // 2,
            "y": viewport["y"] + (viewport["height"] - height * tile) // 2,
            "tile": tile, "width": width * tile, "height": height * tile,
            "width_cap": wcap, "height_cap": hcap,
            "bottleneck": "width" if wcap < hcap else "height" if hcap < wcap else "tie"}


def audit():
    after = current_viewport()
    maps = json.loads((ROOT / "assets/maps/statistics.json").read_text())["levels"]
    rows = [{"level": m["level"], "map_width": m["width"], "map_height": m["height"],
             "before": layout(m["width"], m["height"], BEFORE),
             "after": layout(m["width"], m["height"], after)} for m in maps]
    improved = [r["level"] for r in rows if r["after"]["tile"] > r["before"]["tile"]]
    changes = lambda a, b: [r["level"] for r in rows if
                           (r["before"]["tile"], r["after"]["tile"]) == (a, b)]
    return {"before_viewport": BEFORE, "after_viewport": after,
            "header_pixels_reclaimed": after["height"] - BEFORE["height"],
            "level_count": len(rows), "improved_count": len(improved),
            "unchanged_count": len(rows) - len(improved), "improved_levels": improved,
            "minimum_before": min(r["before"]["tile"] for r in rows),
            "minimum_after": min(r["after"]["tile"] for r in rows),
            "maximum_before": max(r["before"]["tile"] for r in rows),
            "maximum_after": max(r["after"]["tile"] for r in rows),
            "maximum_improvement": max(r["after"]["tile"] - r["before"]["tile"] for r in rows),
            "8_to_9_levels": changes(8, 9), "9_to_10_levels": changes(9, 10),
            "bottlenecks_before": dict(Counter(r["before"]["bottleneck"] for r in rows)),
            "bottlenecks_after": dict(Counter(r["after"]["bottleneck"] for r in rows)),
            "levels": rows}


def verify_capture(report, path):
    with path.open(newline="") as stream:
        rows = [{k: int(v) for k, v in row.items()} for row in csv.DictReader(stream)]
    assert len(rows) == report["level_count"], "renderer level count mismatch"
    for expected, actual in zip(report["levels"], rows):
        assert actual["level"] == expected["level"], "renderer level order mismatch"
        for key in ("x", "y", "tile", "width", "height"):
            assert actual[key] == expected["after"][key], f"level {actual['level']} {key} mismatch"


def markdown(report):
    ids = lambda key: ", ".join(map(str, report[key])) or "none"
    before, after = report["before_viewport"], report["after_viewport"]
    lines = ["# Gameplay layout audit", "",
             "Generated by `python3 tools/layout_audit.py`. Geometry comes from pinned map dimensions and the current renderer constants in `include/render.h`.", "",
             f"The gameplay-only 24 px title was removed. The board viewport changes from ({before['x']}, {before['y']}), {before['width']}×{before['height']} to ({after['x']}, {after['y']}), {after['width']}×{after['height']}. The full 24 px is reclaimed. Main and level-select titles remain.", "",
             "The left HUD moves upward by 24 px without resizing its text. HUD right edge is x115; the divider is x120; the board starts no earlier than x124. Board bottom remains at or above y199; softkeys begin at y204. Square tiles use the smaller floored width/height capacity, and both centering margins differ by at most 1 px.", "",
             "Gameplay modals are centered within y4..199 (center y102): the 88 px INIT/win panel starts at y58; the 103 px save-error panel starts at y50. Menu-only load notices retain their prior position.", "",
             f"- Improved: {report['improved_count']}; unchanged: {report['unchanged_count']}.",
             f"- Minimum tile: {report['minimum_before']} → {report['minimum_after']} px; maximum tile: {report['maximum_before']} → {report['maximum_after']} px.",
             f"- Maximum improvement: +{report['maximum_improvement']} px.",
             f"- Improved IDs: {ids('improved_levels')}.",
             f"- 8 → 9 px IDs: {ids('8_to_9_levels')}.",
             f"- 9 → 10 px IDs: {ids('9_to_10_levels')}.", "",
             "Bottleneck counts compare **integer capacities**: width-limited means floor(viewport width/map width) is strictly smaller; height-limited is the reverse. Equal capacities are reported separately as ties, even when the unfloored ratios differ.", "",
             "| Viewport | Width-limited | Height-limited | Ties |", "|---|---:|---:|---:|"]
    for which in ("before", "after"):
        counts = report[f"bottlenecks_{which}"]
        lines.append(f"| {which.title()} | {counts.get('width',0)} | {counts.get('height',0)} | {counts.get('tie',0)} |")
    lines += ["", "Level 59 is 29×20: before, floor(172/20)=8 is the height bottleneck; after, floor(268/29)=floor(196/20)=9 is a tie. Its tile therefore improves from 8 to 9 px.", "",
              "The native capture executable checks all board bounds, centering, HUD gutters, absence of the top title and out-of-screen drawing. `--capture-csv build-host/captures/layout.csv` compares this audit with all 60 actual C renderer layout results. The updated contact sheets use the shared renderer. Physical LCD readability remains **HARDWARE RETEST REQUIRED**.", "",
              "| Level | Map | Before px | After px | Gain | After bottleneck | Board origin |", "|---:|---|---:|---:|---:|---|---|"]
    for row in report["levels"]:
        old, new = row["before"], row["after"]
        lines.append(f"| {row['level']} | {row['map_width']}×{row['map_height']} | {old['tile']} | {new['tile']} | +{new['tile']-old['tile']} | {new['bottleneck']} | {new['x']}, {new['y']} |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--capture-csv", type=Path)
    args = parser.parse_args()
    report = audit()
    if args.capture_csv:
        verify_capture(report, args.capture_csv)
    outputs = {ROOT / "docs/LAYOUT_AUDIT.md": markdown(report),
               ROOT / "docs/validation/layout-audit.json": json.dumps(report, indent=2) + "\n"}
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                parser.error(f"stale {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    print(json.dumps({k: v for k, v in report.items() if k != "levels"}, indent=2))


if __name__ == "__main__":
    main()
